# Generated by Django 5.2.11 on 2026-02-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='video_url',
        ),
        migrations.AddField(
            model_name='module',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
